name: Frontend CI/CD
on:
  push:
    branches:
      - develop
      - main
  pull_request:
    branches:
      - develop
      - main
jobs:
  test:
    name: Test and Lint
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v5
      - name: Setup pnpm
        uses: pnpm/action-setup@v4.1.0
        with:
          version: 10.17.0
      - name: Setup Nodejs
        uses: actions/setup-node@v5
        with:
          node-version: '18'
          cache: "pnpm"
      - name: Install dependencies
        run: pnpm install --frozen-lockfile
      - name: Run linting
        run: pnpm lint
      


